doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        types:
            gender_enum: App\Doctrine\Type\Core\GenderEnumType
            division_role_enum: App\Doctrine\Type\Core\DivisionRoleEnumType
            question_field_type_enum: App\Doctrine\Type\Modules\Survey\QuestionFieldTypeEnumType
            payment_method_type_enum: App\Doctrine\Type\Shop\PaymentMethodTypeEnumType
            delivery_type_enum: App\Doctrine\Type\Shop\DeliveryTypeEnumType
            discount_applies_on_enum: App\Doctrine\Type\Shop\DiscountAppliesOnEnumType
            game_key_type_enum: App\Doctrine\Type\Shop\GameKeyTypeEnumType
            game_key_destination_enum: App\Doctrine\Type\Shop\GameKeyDestinationEnumType
            order_status_enum: App\Doctrine\Type\Shop\OrderStatusEnumType
            order_item_status_enum: App\Doctrine\Type\Shop\OrderItemStatusEnumType
            color_enum: App\Doctrine\Type\Core\ColorEnumType

        mapping_types:
            enum: string

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
