twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - bootstrap_5_layout.html.twig
    globals:
        categoryService: "@App\\Shop\\CategoryService"
        discountService: "@App\\Shop\\Discount\\DiscountService"
        productService: "@App\\Shop\\ProductService"

when@test:
    twig:
        strict_variables: true
